"""add language to posts

Revision ID: 529655fc4efb
Revises: 5992622e52bd
Create Date: 2019-06-16 16:58:31.415446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529655fc4efb'
down_revision = '5992622e52bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
