"""followers

Revision ID: 5992622e52bd
Revises: 8daadc60bae9
Create Date: 2019-05-27 22:19:00.538336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5992622e52bd'
down_revision = '8daadc60bae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
